// COPYRIGHT (C) HARRY CLARK 2025

// FUNCTION POINTER EXAMPLE (NOT SURE IF THIS WILL BE RELEVANT TO PLC IN THE SLIGHTEST BUT
// IT LOOKS TO MIMIC THE FUNCTIONALITY OF FUNCTIONAL PROGRAMMING MUCH LIKE IN FUNCTIONAL PARADIGM LANGUAGES LIKE JAVA OR HASKELL)

// SYSTEM INCLUDES

#include <stdio.h>

// TYPEDEF DECLARATIONS ALLOW FOR US TO RE-USE VARIABLES WITH DIFFERENT
// NAMES ACROSS THE PROGRAM

typedef void(*MEET_PTR)(const char*);
extern void F_PTR_MAIN(void);

// PROTOTYPE FUNCTION

void MEET_HARRY(const char* NAME)
{    
    printf("Hello, %s\n", NAME);
}

void F_PTR_MAIN(void)
{
    // GIVE MEET_PTR A NAME OF MEET

    MEET_PTR MEET;
  
    // DYNAMICALLY ASSIGN MEET TO HARRY
    
    MEET = MEET_HARRY;

    // THE CHAR ARG WILL ACT AS THE "NAME" FROM THE PROTOTYPE FUNC

    MEET("Harry");
}