// COPYRIGHT (C) HARRY CLARK 2025

// STATIC INITIALISER EXAMPLE

// THIS FILE PERTAINS TOWARDS THE DEMONSTRATION OF REPLICATING THE LIKENESS
// OF FUNCTIONAL PROGRAMMING, BY USING THE "." ACCESS MODIFIER TO STATICALLY
// ACCESS STRUCT MEMBERS FOR RE-USE ACROSS YOUR CODE 

// SYSTEM INCLUDES

#include <stdio.h>

typedef struct PERSON
{
    const char* NAME;
    unsigned AGE;
    unsigned DOB;

} PERSON;

// FUNCTION PROTOTYPES
// NORMALLY YOU WOULD DEFINE YOUR FUNCTIONS LIKE THIS IN A HEADER FILE

// THOUGH I CANNOT BE BOTHERED TO MAKE HEADER FILES
// WHEN THESE EXAMPLES DONT REQUIRE INTRINSIC MODULARISATION

PERSON PERSON_INIT(const char*, unsigned, unsigned);
void SHOW_PERSON_DETAILS(PERSON* const P_BASE);
extern void STATIC_MAIN(void);

// ASSIGN THE STRUCTS MEMBERS TO THE LOCAL ARGS OF THE FUNCTION
// THINK OF THIS AS AN ARRAY AND DEFINING EACH ARRAY MEMBER TO EACH CORRESPONDENCE

PERSON PERSON_INIT(const char* NAME, unsigned AGE, unsigned DOB)
{
    PERSON P = 
    {
        .NAME = NAME,
        .AGE = AGE,
        .DOB = DOB
    };

    return P;
}

void SHOW_PERSON_DETAILS(PERSON* const P_BASE)
{
    fputs("PERSON DETAILS: \n",stdout);
    fprintf(stdout, "Name: %s\n", P_BASE->NAME);
    fprintf(stdout, "Age: %u\n", P_BASE->AGE);
    fprintf(stdout, "Date of Birth: %u\n", P_BASE->DOB);
}

void STATIC_MAIN(void)
{
    // ADD WHICH DETAILS TO PRINT OUT 
    // ACCESS THE MEMORY ADDRESS OF THE PERSON STRUCT 

    PERSON P = PERSON_INIT("HARRY", 20, 29042004);
    SHOW_PERSON_DETAILS(&P);
}